FROM httpd:latest

RUN apt update && \
    apt install --no-install-recommends --yes \
    libapache2-mod-auth-openidc

RUN ln -s /usr/lib/apache2/modules/mod_auth_openidc.so /usr/local/apache2/modules/mod_auth_openidc.so
