- name: Create Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: docker/proxy/Dockerfile
    mode: "0644"

- name: Build the Docker image
  community.docker.docker_image:
    build:
      path: docker/proxy
    name: proxy
    tag: latest
    source: build
