- name: Create Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: docker/sso/Dockerfile
    mode: "0644"

- name: Build the Docker image
  community.docker.docker_image:
    build:
      path: docker/sso
    name: sso
    tag: latest
    source: build
