FROM quay.io/keycloak/keycloak:latest as builder

# Disable health and metrics support
ENV KC_HEALTH_ENABLED=false
ENV KC_METRICS_ENABLED=false

# Configure the database vendor
ENV KC_DB={{ sso_db_vendor }}

{# WORKDIR /opt/keycloak

RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/ #}

# Configure Keycloak env vars
{# ENV KC_HOSTNAME=localhost #}
ENV KEYCLOAK_ADMIN={{ sso_admin }}
ENV KEYCLOAK_ADMIN_PASSWORD={{ sso_admin_password }}
ENV KC_DB_USERNAME={{ sso_db_username }}
ENV KC_DB_PASSWORD={{ sso_db_password }}
{# ENV KC_URL=jdbc:postgresql://172.25.0.3:5432/keycloak #}
ENV KC_DB_URL_HOST=sso_db

# Default commands
{# CMD ["start", "--optimized"] #}
CMD ["start-dev"]

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
