- name: Create Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: docker/core_db/Dockerfile
    mode: "0644"

- name: Build the Docker image
  community.docker.docker_image:
    build:
      path: docker/core_db
    name: core_db
    tag: latest
    source: build
